### ISSUE TITLE
Request history panel makes SQL panel log extra queries

### ISSUE THREAD

**Issue by x-yuri** [djsutho/django-debug-toolbar-request-history#18]
The issue here is that `django-debug-toolbar` first executes [`process_response`][1] method of every panel, then disables [instrumentation][2], then runs [`generate_stats`][3]. With Request history panel, `generate_stats` is called when the former processes response, before instrumentation having been disabled.

[1]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L102
[2]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L110
[3]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L132

As a part of generating stats *Request* panel records session data, which makes an SQL request. The request is recorded by SQL panel, since instrumentation has not yet been disabled. As a result in Debug toolbar I see "1 query in x ms." But when I open SQL panel I see no SQL queries. Supposedly because data for the panel are provided by Request history panel. And by the time Request History panel called `generate_stats` on SQL panel, no extra queries were executed.

[4]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/panels/request.py#L57

**Comment by djsutho** [comment]
@x-yuri thanks for the report. Sorry it took me so long to respond. I've pushed up a branch with the added `disable_instrumentation()` call. Can you install it with:

```
pip install --no-deps -U git+https://github.com/djsutho/django-debug-toolbar-request-history.git@disable-instrumentation-before-stats-generation
```

and see if it fixes the issue?

**Comment by x-yuri** [comment]
> Sorry it took me so long to respond

That's okay, and not really long.

Yes, it fixes the issue. And I couldn't see any regressions. I mean, now `disable_instrumentation` is called twice for each panel. Judging from SQL Panel's code it's okay. But may introduce issues with other panels *(third-party ones?)*.

Speaking of which doesn't it makes more sense for Debug Toolbar to disable instrumentation first? Just thinking aloud, your solution is probably good enough.

**Comment by djsutho** [comment]
It's a good point but from the docs for [`disable_instrumentation`](https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.Panel.disable_instrumentation) the call should be idempotent so I think it should be okay (if third-party panels follow the docs). If it does turn out to be an issue it should be fairly easy to disable the call (similar to the way [`generate_stats`](https://github.com/djsutho/django-debug-toolbar-request-history/blob/7a46373f8b95a0d8b09efc8b6afccb49420e392a/ddt_request_history/panels/request_history.py#L173) is).

As for when to call `disable_instrumentation` I think I had to add the call to `generate_stats` (which requires the disabling) due to an `Panel` interface change. From memory the call had to occur at request time but it might be able to be delayed till the stats are required (when selecting a request or displaying a panel). If you want to have a look it might be worth trying to push the `generate_stats` calls somewhere else and avoid requiring the `disable_instrumentation` call.

On another note, this [issue](https://github.com/jazzband/django-debug-toolbar/issues/1032) seems similar (on the request side instead of the response side) so it might be interesting to see how it develops.
